services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hacka-santo-frontend
    volumes:
    - ./frontend:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - hacka-santo_default
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: yarn dev
    container_name: hacka-santo-backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${BACKEND_PORT}:8080'
    environment:
      - NODE_ENV=docker
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USERNAME=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    networks:
      - hacka-santo_default
    env_file:
      - ./backend/.env
    depends_on:
      - hacka-santo-db

  hacka-santo-db:
    image: postgres
    container_name: hacka-santo-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - hacka-santo_pgdata:/var/lib/postgresql/data
    networks:
      - hacka-santo_default

networks:
  hacka-santo_default:
    driver: bridge

volumes:
  hacka-santo_pgdata: